//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    internal class Product_TagsMetaData
    {
    }
}

//CREATE TABLE Product_Tags
//(
//	TagID int IDENTITY(1,1) NOT NULL,
//	ProductID int NOT NULL,
//	Tag nvarchar(250) NOT NULL
//)
//GO

//ALTER TABLE Product_Tags ADD CONSTRAINT PK_TagID
//PRIMARY KEY CLUSTERED (TagID)
//GO

//ALTER TABLE Product_Tags ADD CONSTRAINT FK_Product__Tags_Products 
//FOREIGN KEY(ProductID) REFERENCES Products(ProductID)
//	ON UPDATE  NO ACTION 
//	ON DELETE  NO ACTION 
//GO