//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace DataLayer
{
    public class Product_GalleriesMetaData
    {
        [Key]
        public int GalleryID { get; set; }

        [Display(Name = "کالا")]
        public int ProductID { get; set; }

        [Display(Name = "تصویر")]
        public string ImageName { get; set; }
    }
}

//CREATE TABLE Product_Galleries
//(
//	GalleryID int IDENTITY(1,1) NOT NULL,
//    ProductID int NOT NULL,
//    ImageName varchar(50) NOT NULL
//)
//GO

//ALTER TABLE Product_Galleries ADD CONSTRAINT PK_GalleryID
//PRIMARY KEY CLUSTERED (GalleryID)
//GO

//ALTER TABLE Product_Galleries ADD CONSTRAINT FK_Product_Galleries_Products 
//FOREIGN KEY(ProductID) REFERENCES Products(ProductID)

//    ON UPDATE  NO ACTION 
//	ON DELETE  NO ACTION 
//GO