//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace DataLayer
{
    public class ProductsMetaData
    {
        [Key]
        public int ProductID { get; set; }

        [Display(Name = "عنوان")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        [MaxLength(350)]
        public string Title { get; set; }

        [Display(Name = "توضیح مختصر")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        [MaxLength(500)]
        [DataType(DataType.MultilineText)]
        public string ShortDescription { get; set; }

        [Display(Name = "متن")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        [DataType(DataType.MultilineText)]
        [AllowHtml]
        public string Text { get; set; }

        [Display(Name = "قیمت")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public int Price { get; set; }

        [Display(Name = "تصویر")]
        public string ImageName { get; set; }

        [Display(Name = "تاریخ ایجاد")]
        public System.DateTime CreateDate { get; set; }
    }
}

//CREATE TABLE Products
//(
//	ProductID int IDENTITY(1,1) NOT NULL,
//    Title nvarchar(350) NOT NULL,
//    ShortDescription nvarchar(500) NOT NULL,

//    [Text] nvarchar(max) NOT NULL,
//    Price int NOT NULL,
//    ImageName varchar(50) NOT NULL,
//    CreateDate datetime NOT NULL
//)
//GO

//ALTER TABLE Products ADD CONSTRAINT PK_Products
//PRIMARY KEY CLUSTERED (ProductID)
//GO