//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace DataLayer
{
    public class Product_FeaturesMetaData
    {
        [Key]
        public int PF_ID { get; set; }

        [Display(Name = "محصول")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public int ProductID { get; set; }

        [Display(Name = "ویژگی")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public int FeatureID { get; set; }

        [Display(Name = "مقدار")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public string Value { get; set; }
    }
}

//CREATE TABLE Product_Features
//(
//	PF_ID INT NOT NULL IDENTITY(1,1) , 
//	ProductID INT NOT NULL ,
//    FeatureID INT NOT NULL ,
//    [Value] NVARCHAR (20)
//)
//GO

//ALTER TABLE Product_Features ADD CONSTRAINT PK_ProductFeatures
//PRIMARY KEY CLUSTERED (PF_ID)
//GO

//ALTER TABLE Product_Features ADD CONSTRAINT FK_ProductFeatures_Products
//FOREIGN KEY (ProductID) REFERENCES Products(ProductID)
//GO

//ALTER TABLE Product_Features ADD CONSTRAINT FK_ProductFeatures_Features
//FOREIGN KEY (FeatureID) REFERENCES Features(FeatureID)
//GO