//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    internal class Product_Selected_GroupsMetaData
    {

    }
}

//CREATE TABLE Product_Selected_Groups
//(
//	PG_ID int IDENTITY(1,1) NOT NULL,
//	ProductID int NOT NULL,
//	GroupID int NOT NULL,
//)
//GO

//ALTER TABLE Product_Selected_Groups ADD CONSTRAINT PK_PG_ID
//PRIMARY KEY CLUSTERED (PG_ID)
//GO

//ALTER TABLE Product_Selected_Groups ADD CONSTRAINT FK_Product_Selected_Groups_ProductGroups 
//FOREIGN KEY(GroupID) REFERENCES ProductGroups(GroupID)
//	ON UPDATE  NO ACTION 
//	ON DELETE  NO ACTION 
//GO

//ALTER TABLE Product_Selected_Groups ADD CONSTRAINT FK_Prodct_Selected_Groups_Products 
//FOREIGN KEY(ProductID) REFERENCES Products(ProductID)
//	ON UPDATE  NO ACTION 
//	ON DELETE  NO ACTION 
//GO