//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;

namespace DataLayer
{
    public class ProductGroupsMetaData
    {
        [Key]
        public int GroupID { get; set; }

        [Display(Name = "عنوان گروه")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public string GroupTitle { get; set; }

        public Nullable<int> ParentID { get; set; }
    }
}

//USE MyEShop
//GO

//CREATE TABLE ProductGroups
//(
//	GroupID INT  NOT NULL,
//    GroupTitle NVARCHAR(400) NOT NULL,
//    ParentID INT NULL
//)
//GO

//ALTER TABLE ProductGroups ADD CONSTRAINT PK_ProductGroups
//PRIMARY KEY CLUSTERED (GroupID)
//GO

//ALTER TABLE ProductGroups ADD CONSTRAINT FK_ProductGroups
//FOREIGN KEY(ParentID) REFERENCES ProductGroups(GroupID)

//    ON UPDATE  NO ACTION 
//	ON DELETE  NO ACTION 
//GO

//INSERT ProductGroups (GroupID, GroupTitle, ParentID) VALUES(1, N'الکترونیک', NULL)
//INSERT ProductGroups(GroupID, GroupTitle, ParentID) VALUES(2, N'صوتی و تصویری', 1)
//INSERT ProductGroups(GroupID, GroupTitle, ParentID) VALUES(3, N'تلویزیون', 1)
//INSERT ProductGroups(GroupID, GroupTitle, ParentID) VALUES(5, N'لوازم شخصی', NULL)
//INSERT ProductGroups(GroupID, GroupTitle, ParentID) VALUES(6, N'مسواک', 5)
//INSERT ProductGroups(GroupID, GroupTitle, ParentID) VALUES(7, N'حوله', 5)
//INSERT ProductGroups(GroupID, GroupTitle, ParentID) VALUES(8, N'گوشی', 5)
//INSERT ProductGroups(GroupID, GroupTitle, ParentID) VALUES(9, N'صنایع دستی', NULL)
//INSERT ProductGroups(GroupID, GroupTitle, ParentID) VALUES(10, N'کیف', 9)
//INSERT ProductGroups(GroupID, GroupTitle, ParentID) VALUES(11, N'کفش', 9)
//INSERT ProductGroups(GroupID, GroupTitle, ParentID) VALUES(12, N'لوازم ورزشی', NULL)