//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    public class UsersMetaData
    {
        public int UserID { get; set; }
        public int RoleID { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string ActiveCode { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime RegisterDate { get; set; }

        public virtual Roles Roles { get; set; }
    }
}

//CREATE TABLE Users
//(
//	  UserID INT IDENTITY NOT NULL,
//    RoleID INT NOT NULL ,
//    UserName NVARCHAR (250) NOT NULL,
//    Email NVARCHAR (250) NOT NULL,
//    Password VARCHAR (200) NOT NULL,
//    ActiveCode VARCHAR (50) NOT NULL,
//    IsActive BIT NOT NULL ,
//    RegisterDate DATETIME NOT NULL 
//)
//GO

//ALTER TABLE Users ADD CONSTRAINT PK_Users
//PRIMARY KEY CLUSTERED (UserID)
//GO


//ALTER TABLE Users ADD CONSTRAINT FK_Users_Roles
//FOREIGN KEY (RoleID) REFERENCES Roles(RoleID)
//GO

//ALTER TABLE Users ADD CONSTRAINT UK_UserName
//UNIQUE NONCLUSTERED (UserName)
//GO
