//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace DataLayer
{
    public class UsersMetaData
    {

        public int UserID { get; set; }

        [Display(Name = "نقش کاربر")]
        public int RoleID { get; set; }

        [Display(Name = "نام کاربری")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public string UserName { get; set; }

        [Display(Name = "ایمیل")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        [EmailAddress(ErrorMessage = "ایمیل وارد شده معتبر نمیباشد")]
        public string Email { get; set; }

        [Display(Name = "کلمه عبور")]
        [Required(ErrorMessage = "لطفا {0} را وارد کنید")]
        public string Password { get; set; }

        [Display(Name = "کد فعال سازی")]
        public string ActiveCode { get; set; }

        [Display(Name = "وضعیت")]
        public bool IsActive { get; set; }

        [Display(Name = "تاریخ ثبت نام")]
        public System.DateTime RegisterDate { get; set; }

        public virtual Roles Roles { get; set; }
    }
}

//CREATE TABLE Users
//(
//	  UserID INT IDENTITY NOT NULL,
//    RoleID INT NOT NULL ,
//    UserName NVARCHAR (250) NOT NULL,
//    Email NVARCHAR (250) NOT NULL,
//    Password VARCHAR (200) NOT NULL,
//    ActiveCode VARCHAR (50) NOT NULL,
//    IsActive BIT NOT NULL ,
//    RegisterDate DATETIME NOT NULL 
//)
//GO

//ALTER TABLE Users ADD CONSTRAINT PK_Users
//PRIMARY KEY CLUSTERED (UserID)
//GO


//ALTER TABLE Users ADD CONSTRAINT FK_Users_Roles
//FOREIGN KEY (RoleID) REFERENCES Roles(RoleID)
//GO

//ALTER TABLE Users ADD CONSTRAINT UK_UserName
//UNIQUE NONCLUSTERED (UserName)
//GO
